site_name: PyPatches Documentation

theme:
  name: "readthedocs"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - from unittest.mock import MagicMock as mock
            - sys.modules["pysquishy"] = mock()
            - sys.modules["pysquishy.squishy"] = mock()
            - sys.modules["pysquishy.clang"] = mock()
